services:
  priviblur:
    image: ghcr.io/dsbok/priviblur:master
    container_name: priviblur
    restart: unless-stopped
    ports:
      - "0.0.0.0:8009:8000"
    environment:
      - PRIVIBLUR_DEPLOYMENT_HOST=0.0.0.0
      - PRIVIBLUR_DEPLOYMENT_PORT=8000
      - PRIVIBLUR_DEPLOYMENT_HTTPS=true
      - PRIVIBLUR_DEPLOYMENT_WORKERS=4
      # Uncomment to allow viewing blogs that require being logged in
      # - PRIVIBLUR_TUMBLR_AUTHORIZATION=Bearer YOUR_TOKEN_HERE
